CREATE TABLE IF NOT EXISTS anggota (
    id_anggota BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    id_user BIGINT REFERENCES pengguna(id_pengguna) ON DELETE CASCADE,
    nim VARCHAR(20) NOT NULL UNIQUE,
    program_studi VARCHAR(100) NOT NULL,
    angkatan INT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    tautan VARCHAR(255),
    files VARCHAR(255),
    dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    diubah_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);