CREATE TABLE IF NOT EXISTS anggota (
    id_anggota BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    id_user BIGINT REFERENCES users(id_user) ON DELETE CASCADE,
    nim VARCHAR(20) NOT NULL UNIQUE,
    nama_lengkap VARCHAR(100) NOT NULL,
    program_studi VARCHAR(100) NOT NULL,
    angkatan INT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);