CREATE TABLE IF NOT EXISTS user (
    id_user PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    nama_lengkap VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
)