CREATE TABLE IF NOT EXISTS pengguna(
    id_pengguna BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    id_peran BIGINT REFERENCES roles(id_role) ON DELETE CASCADE,
    nama_lengkap VARCHAR(100) NOT NULL,
    nama_pengguna VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    sandi VARCHAR(100) NOT NULL,
    nomor_telepon VARCHAR(255),
    foto_pengguna VARCHAR(255),
    status_aktif BOOLEAN NOT NULL DEFAULT TRUE,
    dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    diperbarui_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
