CREATE TABLE IF NOT EXISTS user(
    id_user BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    id_role BIGINT REFERENCES roles(id_role) ON DELETE CASCADE,
    nama_lengkap VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    no_hp VARCHAR(20),
    foto VARCHAR(255),
    is_aktif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
